// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions; // Temporarily disabled
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Mock FirebaseOptions for development
class FirebaseOptions {
  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String? authDomain;
  final String? storageBucket;
  final String? iosBundleId;

  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    this.authDomain,
    this.storageBucket,
    this.iosBundleId,
  });
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcynXU45CFDyLSgvOTTk_6K5rRZurR9d0',
    appId: '1:599937649684:android:ca1993f6b842bff29bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    authDomain: 'ics-app-f2598.firebaseapp.com',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcynXU45CFDyLSgvOTTk_6K5rRZurR9d0',
    appId: '1:599937649684:android:ca1993f6b842bff29bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfh52L-Qx1zLxogasNrPhyvpRkRYufYA',
    appId: '1:599937649684:ios:21bf2a17ede22eb29bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
    iosBundleId: 'com.example.icsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXfh52L-Qx1zLxogasNrPhyvpRkRYufYA',
    appId: '1:599937649684:ios:21bf2a17ede22eb29bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
    iosBundleId: 'com.example.icsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcynXU45CFDyLSgvOTTk_6K5rRZurR9d0',
    appId: '1:599937649684:android:ca1993f6b842bff29bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    authDomain: 'ics-app-f2598.firebaseapp.com',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
  );
}
