// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcynXU45CFDyLSgvOTTk_6K5rRZurR9d0',
    appId: '1:599937649684:web:3ce2a1a2c1737cab9bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    authDomain: 'ics-app-f2598.firebaseapp.com',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcynXU45CFDyLSgvOTTk_6K5rRZurR9d0',
    appId: '1:599937649684:android:de03d4e430984dfc9bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfh52L-Qx1zLxogasNrPhyvpRkRYufYA',
    appId: '1:599937649684:ios:aa4fcb20f3cf22b29bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
    iosClientId:
        '599937649684-04o7tctnq16d6i4ua54q55un2d69lenr.apps.googleusercontent.com',
    iosBundleId: 'com.ali.koyuncu.ics.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXfh52L-Qx1zLxogasNrPhyvpRkRYufYA',
    appId: '1:599937649684:ios:aa4fcb20f3cf22b29bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
    iosClientId:
        '599937649684-04o7tctnq16d6i4ua54q55un2d69lenr.apps.googleusercontent.com',
    iosBundleId: 'com.ali.koyuncu.ics.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcynXU45CFDyLSgvOTTk_6K5rRZurR9d0',
    appId: '1:599937649684:web:3ce2a1a2c1737cab9bab01',
    messagingSenderId: '599937649684',
    projectId: 'ics-app-f2598',
    authDomain: 'ics-app-f2598.firebaseapp.com',
    storageBucket: 'ics-app-f2598.firebasestorage.app',
  );
}
